// apps/web/src/app/app/player/page.tsx
'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { VideoPlayer } from './VideoPlayer'
import styles from './page.module.css'

export default function PlayerPage() {
  const [url, setUrl] = useState('')
  const [title, setTitle] = useState('')
  const [episode, setEpisode] = useState(0)
  const [error, setError] = useState('')

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem('saizen:lastStream')
      if (!raw) {
        setError('No stream queued. Play something from an anime page first.')
        return
      }
      const data = JSON.parse(raw) as { url: string; title: string; episode: number }
      setUrl(data.url)
      setTitle(data.title)
      setEpisode(data.episode)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    }

    // Native playback owns cleanup via player dismiss → stopAndPurge.
    // Do not call deleteTorrents on unmount (React Strict Mode remounts would
    // kill a live stream mid-play).
  }, [])

  const heading = title
    ? episode
      ? `${title} · Ep ${episode}`
      : title
    : 'Player'

  return (
    <>
      <Link className="muted" href="/">
        ← Home
      </Link>
      <h1 className={styles.h1}>{heading}</h1>

      {error ? (
        <p style={{ color: 'var(--danger)' }}>{error}</p>
      ) : url ? (
        <>
          <VideoPlayer src={url} title={heading} />
          <p className={`muted ${styles.tiny}`}>{url}</p>
          <p className={`muted ${styles.hint}`}>
            Space / K play · J / L ±10s · ← → seek · ↑ ↓ volume · M mute · F fullscreen
          </p>
        </>
      ) : null}
    </>
  )
}

// apps/web/src/routes/app/player/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  let url = ''
  let title = ''
  let episode = 0
  let error = ''

  onMount(() => {
    try {
      const raw = sessionStorage.getItem('saizen:lastStream')
      if (!raw) {
        error = 'No stream queued. Play something from an anime page first.'
        return
      }
      const data = JSON.parse(raw) as { url: string; title: string; episode: number }
      url = data.url
      title = data.title
      episode = data.episode
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
    }
  })
</script>

<svelte:head>
  <title>Player — Saizen</title>
</svelte:head>

<a class="muted" href="#/">← Home</a>
<h1>{title || 'Player'}</h1>
{#if episode}<p class="muted">Episode {episode}</p>{/if}

{#if error}
  <p style="color: var(--danger)">{error}</p>
{:else if url}
  <p class="muted tiny">{url}</p>
  <!-- Web-only HTML5 player for progressive HTTP test streams -->
  <video class="vid" src={url} controls autoplay playsinline>
    <track kind="captions" />
  </video>
{/if}

<style>
  h1 {
    margin: 0.5rem 0 0.25rem;
  }
  .vid {
    width: 100%;
    max-height: 70vh;
    background: #000;
    border-radius: 10px;
    margin-top: 1rem;
  }
  .tiny {
    font-size: 0.75rem;
    word-break: break-all;
  }
</style>
