// apps/web/src/app/app/search/page.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { searchAnime, displayTitle, type AnimeMedia } from '@/lib/anilist'
import { ensureExtensions, hasAdultExtensionsEnabled } from '@/lib/extensions'
import { PageHeader, PosterCard, PosterGrid } from '@/components/saizen'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export default function SearchPage() {
  const [term, setTerm] = useState('')
  const [results, setResults] = useState<AnimeMedia[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [includeAdult, setIncludeAdult] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    inputRef.current?.focus()
    void ensureExtensions().then(() => {
      setIncludeAdult(hasAdultExtensionsEnabled())
    })
  }, [])

  async function run(e?: React.FormEvent) {
    e?.preventDefault()
    if (!term.trim()) return
    setLoading(true)
    setError('')
    try {
      setResults(await searchAnime(term.trim(), 1, { includeAdult }))
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <PageHeader title="Search" description="Find anime by romaji, English, or native title." dense />

      <form className="flex gap-2" onSubmit={(e) => void run(e)}>
        <Input
          ref={inputRef}
          className="min-h-11"
          placeholder="Romaji / English / Japanese title"
          value={term}
          onChange={(e) => setTerm(e.target.value)}
        />
        <Button type="submit" size="lg" className="min-h-11 px-5" disabled={loading}>
          {loading ? '…' : 'Search'}
        </Button>
      </form>

      {includeAdult ? (
        <p className="mt-2 text-xs text-muted-foreground">
          Adult titles included (hentai extension enabled).
        </p>
      ) : null}

      {error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}

      <PosterGrid className="mt-5">
        {results.map((media) => (
          <PosterCard
            key={media.id}
            size="sm"
            className="w-full min-w-0"
            href={`/app/anime/?id=${media.id}`}
            image={media.coverImage?.large}
            title={displayTitle(media)}
            score={media.averageScore}
            format={media.format}
            year={media.seasonYear}
          />
        ))}
      </PosterGrid>
    </>
  )
}

// apps/web/src/routes/app/search/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { searchAnime, displayTitle, type AnimeMedia } from '$lib/anilist'

  let term = ''
  let results: AnimeMedia[] = []
  let loading = false
  let error = ''

  async function run() {
    if (!term.trim()) return
    loading = true
    error = ''
    try {
      results = await searchAnime(term.trim())
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
    } finally {
      loading = false
    }
  }

  onMount(() => {
    const input = document.getElementById('q') as HTMLInputElement | null
    input?.focus()
  })
</script>

<svelte:head>
  <title>Search — Saizen</title>
</svelte:head>

<h1>Search</h1>
<form
  class="row"
  on:submit|preventDefault={run}
>
  <input id="q" placeholder="Romaji / English / Japanese title" bind:value={term} />
  <button class="btn btn-primary" type="submit" disabled={loading}>
    {loading ? '…' : 'Search'}
  </button>
</form>

{#if error}
  <p style="color: var(--danger)">{error}</p>
{/if}

<div class="grid" style="margin-top: 1.25rem">
  {#each results as media (media.id)}
    <a class="card poster" href={`#/app/anime/${media.id}`}>
      {#if media.coverImage?.large}
        <img src={media.coverImage.large} alt={displayTitle(media)} loading="lazy" />
      {/if}
      <div class="meta">
        <strong>{displayTitle(media)}</strong>
      </div>
    </a>
  {/each}
</div>

<style>
  h1 {
    margin: 0 0 1rem;
  }
  .row {
    display: flex;
    gap: 0.5rem;
  }
  input {
    flex: 1;
    padding: 0.6rem 0.75rem;
    border-radius: 8px;
    border: 1px solid var(--border);
    background: var(--surface);
    color: var(--text);
  }
  .poster img {
    aspect-ratio: 2 / 3;
    object-fit: cover;
    width: 100%;
  }
  .meta {
    padding: 0.55rem 0.65rem;
  }
  .meta strong {
    font-size: 0.85rem;
  }
</style>
